# Generated by Django 3.2 on 2024-01-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirmation_code',
            new_name='user_confirmation_code',
        ),
    ]
