# Generated by Django 3.2 on 2024-01-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_confirmation_code_user_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_confirmation_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Код подтверждения'),
        ),
    ]
